INFO logger 2024-02-01 10:26:39,792 | data_utils.py:383 | Observations info in ElBorn
INFO logger 2024-02-01 10:26:39,793 | data_utils.py:384 | 	Total number of samples:  4192
INFO logger 2024-02-01 10:26:39,793 | data_utils.py:385 | 	Number of samples for training: 3354
INFO logger 2024-02-01 10:26:39,793 | data_utils.py:386 | 	Number of samples for validation:  838
INFO logger 2024-02-01 10:26:39,794 | data_utils.py:383 | Observations info in LesCorts
INFO logger 2024-02-01 10:26:39,795 | data_utils.py:384 | 	Total number of samples:  6892
INFO logger 2024-02-01 10:26:39,795 | data_utils.py:385 | 	Number of samples for training: 5514
INFO logger 2024-02-01 10:26:39,795 | data_utils.py:386 | 	Number of samples for validation:  1378
INFO logger 2024-02-01 10:26:39,797 | data_utils.py:383 | Observations info in PobleSec
INFO logger 2024-02-01 10:26:39,797 | data_utils.py:384 | 	Total number of samples:  15927
INFO logger 2024-02-01 10:26:39,797 | data_utils.py:385 | 	Number of samples for training: 12742
INFO logger 2024-02-01 10:26:39,797 | data_utils.py:386 | 	Number of samples for validation:  3185
INFO logger 2024-02-01 10:26:39,798 | data_utils.py:389 | Observations info using all data
INFO logger 2024-02-01 10:26:39,798 | data_utils.py:390 | 	Total number of samples:  27011
INFO logger 2024-02-01 10:26:39,798 | data_utils.py:391 | 	Number of samples for training: 21610
INFO logger 2024-02-01 10:26:39,798 | data_utils.py:392 | 	Number of samples for validation:  5401
INFO logger 2024-02-01 10:26:39,799 | data_utils.py:118 | Using Flooring and Capping and with params: {'ElBorn': (10, 90), 'LesCorts': (10, 90), 'PobleSec': (5, 95)}
INFO logger 2024-02-01 10:26:40,422 | server.py:62 | Initializing client manager...
INFO logger 2024-02-01 10:26:40,422 | server.py:69 | Registering clients...
INFO logger 2024-02-01 10:26:40,423 | client_manager.py:66 | Registered client with id: ElBorn
INFO logger 2024-02-01 10:26:40,423 | client_manager.py:66 | Registered client with id: LesCorts
INFO logger 2024-02-01 10:26:40,423 | client_manager.py:66 | Registered client with id: PobleSec
INFO logger 2024-02-01 10:26:40,423 | server.py:73 | Client manager initialized!
INFO logger 2024-02-01 10:26:40,423 | server.py:55 | Aggregation algorithm: FedAvg()
INFO logger 2024-02-01 10:26:40,423 | client_manager.py:88 | Parameter c=0.0. Sampled 1 client(s): ['LesCorts']
Clients participating training are: dict_keys(['ElBorn', 'LesCorts', 'PobleSec'])
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.17.2 -- An enhanced Interactive Python. Type '?' for help.
False
{'MSE': 0.22578001,
 'RMSE': 0.47516314064054743,
 'MAE': 0.36741677,
 'R^2': -3.081132162009889,
 'NRMSE': 2.2760502830162253}
{'MSE': 0.22578001,
 'RMSE': 0.47516314064054743,
 'MAE': 0.36741677,
 'R^2': -3.081132162009889,
 'NRMSE': 2.2760502830162253}
{'ElBorn': {'MSE': 0.105051816,
  'RMSE': 0.3241169781264106,
  'MAE': 0.3020049,
  'R^2': -63.903260299770366,
  'NRMSE': 6.775239697116192},
 'LesCorts': {'MSE': 0.28481242,
  'RMSE': 0.5336781994859947,
  'MAE': 0.46845213,
  'R^2': -314.91407827790897,
  'NRMSE': 8.28366111459727},
 'PobleSec': {'MSE': 0.22578001,
  'RMSE': 0.47516314064054743,
  'MAE': 0.36741677,
  'R^2': -3.081132162009889,
  'NRMSE': 2.2760502830162253}}
INFO logger 2024-02-01 10:31:28,969 | server.py:87 | Starting FL rounds
INFO logger 2024-02-01 10:31:28,969 | client_manager.py:88 | Parameter c=1.0. Sampled 3 client(s): ['LesCorts', 'ElBorn', 'PobleSec']
[31mStarting poisoning...!
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1276, in __call__
    self.handler((etype, evalue, etb))
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1265, in handler
    ostream.write(self.text(etype, evalue, etb))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/IPython/core/ultratb.py", line 446, in text
    tb_list = self.structured_traceback(etype, value, tb,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1326, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1173, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1088, in format_exception_as_a_whole
    frames.append(self.format_record(record))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/IPython/core/ultratb.py", line 970, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
    ^^^^^^^^^^^^^^^^
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/IPython/core/ultratb.py", line 792, in lines
    return self._sd.lines
           ^^^^^^^^^^^^^^
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/stack_data/core.py", line 681, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
                             ^^^^^^^^^^^^^^^^^^^^
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/stack_data/core.py", line 660, in executing_piece
    return only(
           ^^^^^
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/executing/executing.py", line 116, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
Original exception was:
Traceback (most recent call last):
  File "/home/judy/code/Fed-Time-Series-Forecasting/main.py", line 116, in <module>
    main(args)
  File "/home/judy/code/Fed-Time-Series-Forecasting/main.py", line 46, in main
    global_model, history = fit(
                            ^^^^
  File "/home/judy/code/Fed-Time-Series-Forecasting/fl_trainer.py", line 109, in fit
    model_params, history = server.fit(args.fl_rounds, args.fraction, use_carbontracker=use_carbontracker,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/judy/code/Fed-Time-Series-Forecasting/ml/fl/server/server.py", line 102, in fit
    self.fit_round(fl_round=fl_round,
  File "/home/judy/code/Fed-Time-Series-Forecasting/ml/fl/server/server.py", line 147, in fit_round
    num_test_examples: List[int] = []
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/judy/code/Fed-Time-Series-Forecasting/ml/fl/server/server.py", line 186, in fit_client
  File "/home/judy/code/Fed-Time-Series-Forecasting/ml/fl/client_proxy.py", line 37, in fit
    return self.client.fit(model)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/judy/code/Fed-Time-Series-Forecasting/ml/fl/torch_client.py", line 116, in fit
    self.net: torch.nn.Module = train(model=self.net, train_loader=self.train_loader, test_loader=self.val_loader,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/judy/code/Fed-Time-Series-Forecasting/ml/utils/train_utils.py", line 97, in train
    loss.backward()
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/judy/miniconda3/envs/judy/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt